version: "3.8"
services:

  marketplace: 
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS_HOST: recommendations
    image: spencerofwiti/microservices-grpc-marketplace
    networks:
      - microservices
    ports:
      - 5000:5000

  recommendations:
    build:
      context: .
      dockerfile: recommendations/Dockerfile
    image: spencerofwiti/microservices-grpc-recommendations
    networks:
      - microservices

networks:
  microservices:
